language: scala
scala:
- 2.12.7

script:
- sbt clean coverage test coverageReport
- cd Tui
- sbt clean coverage test coverageReport
- cd ../FileIO
- sbt clean coverage test coverageReport

after_success:
- sbt coverageReport coveralls
- cd Tui
- sbt coverageReport coveralls
- cd ../FileIO
- sbt coverageReport coveralls
